website/__init__.py
from flask import Flask


def start_app():
    from .views import views
    app = Flask(__name__)
    app.register_blueprint(views)
    return app

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .api import Api
import random


views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
def index():
    if request.method == "POST":
        query = request.form.get("search")
        return redirect(url_for('views.result', query=query))
    unsplash_api = Api()
    page_on = random.randint(1, 5)
    images = format_api(unsplash_api.get_images())
    art_image = random.choice(unsplash_api.query("art", page_on)["results"])
    return render_template(
        "index.html",
        art_image=art_image["urls"]["full"],
        images=images
    )


@views.route("/result/<query>")
def result(query):
    unsplash_api = Api()
    page_on = random.randint(1, 5)
    images = format_api(unsplash_api.query(
        query=query, page_on=page_on)["results"])
    art_image = random.choice(unsplash_api.query("art", page_on)["results"])
    return render_template(
        "result.html",
        images=images,
        art_image=art_image["urls"]["full"]
    )


def format_api(api: list):
    result = []
    for i in range(3):
        cols = []
        j = i
        while True:
            try:
                image = api[j]
                cols.append(image)
                j += 3
            except IndexError:
                break
        result.append(cols)
    return result

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='index.css') }}"
    />
    <link rel="icon" href="{{ url_for('static', filename='logo.ico') }}" />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <title>Vitrine World class image and art gallery</title>
  </head>

  <body>
    <div id="mobile">
      <h1 style="color: black">
        This website is not design at your screen size
      </h1>
    </div>
    <div class="header">
      <img src="{{ art_image }}" alt="header-img" />
      <nav>
        <span class="nav-title">Vitrine</span>
      </nav>
      <div class="nav-center">
        <h1>World class image and art gallery.</h1>
        <div class="input">
          <form action="{{ url_for('views.index') }}" method="POST">
            <input type="text" placeholder="Search" name="search" />
            <button
              class="ripple-btn"
              type="submit"
              style="border-radius: 50px"
            >
              <i class="material-icons"> search </i>
            </button>
          </form>
        </div>
      </div>
    </div>
    <div class="body">
      <div class="grid">
        {% for col in images %}
        <div class="col-grid">
          {% for image in col %}
          <div class="art-content">
            <img
              src="{{ image['urls']['small'] }}"
              alt="img"
              id="{{ image['id'] }}"
            />
            <div class="text-content">
              <h2>{{ image.user.name }}</h2>
              {% if image.alt_description %}
              <p>{{ image.alt_description }}</p>
              {% elif image.discription%}
              <p>{{ image.discription }}</p>
              {% else %}
              <p>This image don't have any discryption</p>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
    </div>
    <script src="{{ url_for('static', filename='index.js') }}"></script>
  </body>
</html>

website/templates/result.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{{ url_for('static', filename='logo.ico') }}" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='index.css') }}"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <title>Vitrine World class image and art gallery</title>
  </head>

  <body>
    <div id="mobile">
      <h1 style="color: black">
        This website is not design at your screen size
      </h1>
    </div>
    <div class="header">
      <img src="{{ art_image }}" alt="header-img" />
      <nav>
        <span class="nav-title">Vitrine</span>
      </nav>
      <div class="nav-center">
        <h1>World class image and art gallery.</h1>
        <div class="input">
          <form action="{{ url_for('views.index') }}" method="POST">
            <input type="text" placeholder="Search" name="search" />
            <button
              class="ripple-btn"
              type="submit"
              style="border-radius: 50px"
            >
              <i class="material-icons"> search </i>
            </button>
          </form>
        </div>
      </div>
    </div>
    <div class="body">
      <div class="grid">
        {% for col in images %}
        <div class="col-grid">
          {% for image in col %}
          <div class="art-content">
            <img
              src="{{ image['urls']['small'] }}"
              alt="img"
              id="{{ image['id'] }}"
            />
            <div class="text-content">
              <h2>{{ image.user.name }}</h2>
              {% if image.alt_description %}
              <p>{{ image.alt_description }}</p>
              {% elif image.discription%}
              <p>{{ image.discription }}</p>
              {% else %}
              <p>This image don't have any discryption</p>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
    </div>
    <script src="{{ url_for('static', filename='index.js') }}"></script>
  </body>
</html>